version: "3.8"

services:
    polaris-postgres:
        image: postgres
        container_name: polaris-postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=${POSTGRES_ROOT_USER_NAME}
            - POSTGRES_PASSWORD=${POSTGRES_ROOT_USER_PASSWORD}
            - POSTGRES_DB=${POSTGRES_ROOT_DB}
            - POSTGRES_POLARIS_USER_NAME
            - POSTGRES_POLARIS_USER_PASSWORD
            - POLARIS_DB
        volumes:
            - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
            - polaris-pg-data-volume:/var/lib/postgresql/data
    polaris-redis:
        image: redis
        container_name: polaris-redis
        ports:
            - "6379:6379"
        volumes:
            - polaris-redis-data-volume:/data
    polaris-api:
        build: ./api
        image: polaris/api
        container_name: polaris-api
        restart: on-failure
        ports:
            - "8080:8080"
        environment:
            # - JAVA_OPTS=
            - DB_SERVER_HOST=polaris-postgres
            - DB_SERVER_PORT=5432
            - DB_USER=${POSTGRES_POLARIS_USER_NAME}
            - DB_PASSWORD=${POSTGRES_POLARIS_USER_PASSWORD}
            - DB_NAME=${POLARIS_DB}
            - REDIS_HOST=polaris-redis
            - REDIS_PORT=6379
            - SMTP_SERVER_HOST
            - SMTP_SERVER_PORT
            - SMTP_SERVER_USERNAME
            - SMTP_SERVER_PASSWORD
            - WEBAPP_HOST
            - WEBAPP_PORT
            - WEBAPP_SSL
            - ALLOWED_ORIGINS
            - CONFIG_SERVER_SSL
            # - CONFIG_SERVER_HOST=
            # - CONFIG_SERVER_PORT=
            - SPRING_BOOT_ADMIN_SERVER_SSL
            # - SPRING_BOOT_ADMIN_SERVER_HOST=admin
            # - SPRING_BOOT_ADMIN_SERVER_PORT=8090
            - SPRING_BOOT_ADMIN_USER
            - SPRING_BOOT_ADMIN_PASSWORD
        volumes:
            - ./logs:/logs
        depends_on:
            - polaris-postgres
            - polaris-redis
    polaris-webapp:
        build: ./webapp
        image: polaris/webapp
        container_name: polaris-webapp
        restart: on-failure
        ports:
            - "8888:80"
volumes:
    polaris-pg-data-volume:
    polaris-redis-data-volume:
