#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE ROLE "$POSTGRES_POLARIS_USER_NAME" WITH LOGIN PASSWORD '$POSTGRES_POLARIS_USER_PASSWORD';
    ALTER ROLE "$POSTGRES_POLARIS_USER_NAME" CREATEDB;
    \c "$POSTGRES_DB" "$POSTGRES_POLARIS_USER_NAME"
    CREATE DATABASE "$POLARIS_DB";
    GRANT ALL PRIVILEGES ON DATABASE "$POLARIS_DB" TO "$POSTGRES_POLARIS_USER_NAME";
EOSQL
