FROM adoptopenjdk:11-jre-hotspot as builder
WORKDIR /app
COPY target/*.jar app.jar
RUN java -Djarmode=layertools -jar app.jar extract

FROM adoptopenjdk:11-jre-hotspot
WORKDIR /app
COPY --from=builder /app/dependencies/ ./
COPY --from=builder /app/snapshot-dependencies/ ./
COPY --from=builder /app/spring-boot-loader/ ./
COPY --from=builder /app/application/ ./
EXPOSE 8080
VOLUME /logs
ENTRYPOINT [ "java", "${JAVA_OPTS}", "org.springframework.boot.loader.JarLauncher" ]
